.\" '\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for fuse-zip
.TH "fuse-zip" "1" "January 2014" "FUSE filesystem to read and modify ZIP archives" "FUSE filesystem to read and modify ZIP archives"
.SH "NAME"
fuse\-zip \- a FUSE filesystem for zip archives with write support
.SH "SYNOPSIS"
.\" The general command line
.B fuse\-zip
.RI [\| options \|]
zip\-file
mount\-point
.SH "OPTIONS"
.TP
\fB-h\fP
print help
.TP
\fB-V\fP
print version
.TP
\fB-r\fP
open archive in read\-only mode
.TP
\fB-o opt[,opt...]\fP
mount options
.TP
\fB-f\fP
don't detach from terminal
.TP
\fB-d\fP
turn on debugging, also implies \-f
.PP
If you want to specify character set conversion for file names in archive,
use the following fusermount options:

  \-omodules=iconv,from_code=$charset1,to_code=$charset2

See FUSE documentation for details.
.SH "DESCRIPTION"
.B fuse\-zip
is a fuse filesystem, that enables any program to work with a ZIP archive as though it is a plain directory.
Unlike KIO or Gnome VFS, it can be used in any application without modifications.

Unlike other FUSE filesystems, only fuse\-zip provides write support to ZIP archives.
Also, fuse\-zip is faster that all known implementations on large archives with many files. 

Since version 0.3.0 fuse-zip has support for absolute and parent-relative paths
in file names, but only in read-only mode (-r command line switch). Absolute
paths are displayed under "ROOT" directory, every ".." in path replaced by "UP"
in directory name and "normal" files are placed under "CUR" directory.

Support for UNIX file permissions and owner information has been added in
version 0.4. See
.B PERMISSIONS
for details.
.SH "USAGE"
General usage would look like this

.TS
tab (@);
l l.
1@mkdir\ /tmp/zipArchive
2@fuse\-zip foobar.zip /tmp/zipArchive
3@(do something with the mounted file system)
4@fusermount \-u /tmp/zipArchive
.TE
.PP
Be patient. Wait for fuse-zip process finish after unmounting, especially on a big archives.
.SH "PERMISSIONS"
Access check will not be performed unless
\fB-o default_permissions\fP mount option is given.
.SH "FILES"
.TP 
.if !'po4a'hide' .I /var/log/user.log
see this file in case any errors occur
.SH "SEE ALSO"
.BR fusermount (1).
.SH "LICENSE"
.
This is Free Software; this software is licensed under the LGPL version 3, as published by the Free Software Foundation, or later.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.
.SH "AUTHORS"
.
Alexander Galanin <al@galanin.nnov.ru> http://galanin.nnov.ru/~al
.br 
.
This manual page was originally written by Kirill Zaitsev <teferiincub@gmail.com>. Updated by Alexander Galanin.

