######################################################################
# Automatically generated by qmake (1.07a) Tue Jun 3 23:43:34 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .
INCLUDEPATH += /usr/include/kde

# Input
SOURCES += main.cpp

LIBS += -lkdecore -lkio

